#============================================================================================
# https://github.com/ophub/amlogic-s9xxx-openwrt
# Description: Build OpenWrt
#============================================================================================

name: 通用设备编译固件

on:
  workflow_dispatch:

env:
  FEEDS_CONF: config/openwrt-main/feeds.conf.default
  CONFIG_FILE: config/openwrt-main/config
  DIY_P1_SH: config/openwrt-main/diy-part1.sh
  DIY_P2_SH: config/openwrt-main/diy-part2.sh
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # 🧹 新增：释放磁盘空间
    - name: Free up disk space
      run: |
        echo "🧹 Cleaning up GitHub Actions runner to free space..."
        sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/boost /usr/local/lib/android /opt/hostedtoolcache
        sudo apt-get clean
        df -h

    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk gettext git java-propose-classpath libncurses5-dev libssl-dev python3 python3-distutils python3-setuptools rsync subversion unzip zlib1g-dev

    - name: Clone source code
      run: |
        git clone https://github.com/coolsnowwolf/lede openwrt

    - name: Load custom feeds.conf
      run: |
        [[ -e "${FEEDS_CONF}" ]] && cp -f ${FEEDS_CONF} openwrt/feeds.conf.default

    - name: Update feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Run diy-part1.sh
      run: |
        chmod +x ${DIY_P1_SH}
        ${GITHUB_WORKSPACE}/${DIY_P1_SH}

    - name: Load custom configuration
      run: |
        [[ -d "files" ]] && mv -f files openwrt/files
        [[ -e "${CONFIG_FILE}" ]] && cp -f ${CONFIG_FILE} openwrt/.config

    - name: Run diy-part2.sh
      run: |
        chmod +x ${DIY_P2_SH}
        cd openwrt
        ${GITHUB_WORKSPACE}/${DIY_P2_SH}

    - name: Download package
      run: |
        cd openwrt
        make download -j8

    - name: Compile firmware
      run: |
        cd openwrt
        echo -e "Start compiling using $(nproc) threads..."
        make -j$(nproc) V=s || make -j1 V=s

    - name: Check space usage
      run: df -h

    - name: Upload bin directory
      if: env.UPLOAD_BIN_DIR == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-bin
        path: openwrt/bin

    - name: Upload firmware to release
      if: env.UPLOAD_RELEASE == 'true'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: openwrt-${{ github.run_number }}
        name: OpenWrt Build ${{ github.run_number }}
        draft: false
        prerelease: false
        files: openwrt/bin/targets/**/*
